"""Confined, unprivileged source build handoff."""

from __future__ import annotations

import os
import pathlib
import shutil
import stat
import subprocess
import tempfile
from collections.abc import Callable, Sequence

from .identity import (
    IdentityError,
    UserRecord,
    build_worker_command,
    copy_validated_worker_output,
)
from .settings import InstallationSettings


class WorkerError(RuntimeError):
    """The confined source build failed validation."""


Runner = Callable[[Sequence[str]], subprocess.CompletedProcess[bytes]]


def _copy_source_directory(source: pathlib.Path, destination: pathlib.Path) -> None:
    """Copy a Python source tree while refusing links and generated bytecode."""
    if not source.is_dir() or source.is_symlink():
        raise WorkerError(f"required source directory is unavailable: {source}")
    destination.mkdir(mode=0o700)
    for path in sorted(source.rglob("*")):
        relative = path.relative_to(source)
        if "__pycache__" in relative.parts or path.suffix == ".pyc":
            continue
        if path.is_symlink():
            raise WorkerError(f"source tree contains a symbolic link: {relative}")
        target = destination / relative
        metadata = path.stat()
        if stat.S_ISDIR(metadata.st_mode):
            target.mkdir(mode=0o700, exist_ok=True)
        elif stat.S_ISREG(metadata.st_mode):
            target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
            target.write_bytes(path.read_bytes())
            os.chmod(target, 0o600)
        else:
            raise WorkerError(f"source tree contains a non-regular entry: {relative}")


def _chown_tree(root: pathlib.Path, uid: int, gid: int) -> None:
    for directory, directories, files in os.walk(root):
        base = pathlib.Path(directory)
        os.chown(base, uid, gid)
        os.chmod(base, 0o700)
        for name in directories:
            os.chown(base / name, uid, gid)
            os.chmod(base / name, 0o700)
        for name in files:
            os.chown(base / name, uid, gid)
            os.chmod(base / name, 0o600)


def build_in_confined_worker(
    settings: InstallationSettings,
    *,
    repo_root: pathlib.Path,
    output: pathlib.Path,
    jobs_root: pathlib.Path | None = None,
    runner: Runner,
    user: UserRecord,
) -> None:
    """Build a zipapp as the staging user, validate it, and copy it to root state."""
    jobs = jobs_root or settings.staging_root / "jobs"
    if jobs.is_symlink() or not jobs.is_dir():
        raise WorkerError("staging jobs directory is unavailable or unsafe")
    job = pathlib.Path(tempfile.mkdtemp(prefix="build-", dir=jobs))
    try:
        source_root = job / "source"
        source_root.mkdir(mode=0o700)
        for name in ("src", "tools"):
            _copy_source_directory(repo_root / name, source_root / name)
        artifact_directory = job / "output"
        artifact_directory.mkdir(mode=0o700)
        artifact = artifact_directory / "awgctl"
        _chown_tree(job, user.uid, user.gid)
        command = build_worker_command(
            settings,
            job,
            [
                "/usr/bin/python3",
                str(source_root / "tools/build_release.py"),
                "--output",
                str(artifact),
            ],
            network=False,
        )
        try:
            result = runner(command)
        except (OSError, subprocess.SubprocessError) as exc:
            raise WorkerError("confined source build could not run") from exc
        if result.returncode != 0:
            detail = result.stderr.decode("utf-8", "replace").strip().splitlines()
            raise WorkerError(f"confined source build failed{': ' + detail[-1] if detail else ''}")
        try:
            copy_validated_worker_output(
                artifact,
                output,
                expected_uid=user.uid,
                expected_mode=0o755,
                max_size=16 * 1024 * 1024,
            )
        except IdentityError as exc:
            raise WorkerError(str(exc)) from exc
    finally:
        try:
            job.relative_to(jobs)
        except ValueError as exc:
            raise WorkerError("refusing to clean an unsafe worker path") from exc
        shutil.rmtree(job, ignore_errors=True)
